start_state_joint1: 1.57
start_state_joint2: 1.57
start_state_joint3: 1.57

goal_state_joint1: 1.57
goal_state_joint2: 1.57
goal_state_joint3: 1.57

# planning cost 
length_cost_thre: 16
var_thre: 0.08 # l: 0.02, indicating more strict flight