## base init and goal
start_state_x: 0.0
start_state_y: -0.25
start_state_z: -1.0
start_state_roll: 0.0
start_state_pitch: 0.0
start_state_yaw: 0.0

goal_state_x: 0.0
goal_state_y: 0.0
goal_state_z: 2.5
goal_state_roll: 0.0
goal_state_pitch: 0.0
goal_state_yaw: 0.0

## joint init and goal
start_state_joint1: 0.0 # joint1_pitch
start_state_joint2: 1.57 # joint1_yaw
start_state_joint3: 0.0 # joint2_pitch
start_state_joint4: 1.57 # joint2_yaw
start_state_joint5: 0.0 # joint3_pitch
start_state_joint6: 1.57 # joint3_yaw

goal_state_joint1: 0 # joint1_pitch
goal_state_joint2: 1.57 # joint1_yaw
goal_state_joint3: 0 # joint2_pitch
goal_state_joint4: 1.57 # joint2_yaw
goal_state_joint5: 0 # joint3_pitch
goal_state_joint6: 1.57 # joint3_yaw

## bound
x_low_bound: -1.0
x_high_bound: 1.0
y_low_bound: -1.0
y_high_bound: 1
z_low_bound:  -2.0
z_high_bound: 4.0
pitch_joint_low_bound: -1.58
pitch_joint_high_bound: 1.58
yaw_joint_low_bound: 0
yaw_joint_high_bound: 1.58

# planning cost 
baselink: link1
length_cost_thre: 20

# dist check
var_thre: 0.25 # l: 0.22, s: 0.21; 
# overlap check
edf_max_tilt: 0.075 #0.18
# statics
f_max: 22