debug: true
joint_states_pub_name: /planning/joint_states #can show in urdf file, "/joint_states" for debug
play_file_flag: true
control_test_flag: false #approaching test, "true" for debug
approach_base_link: 1 #approaching base_link
approach_pos_weight_rate: 10.0 #weight algorithm
approach_angle_weight_rate: 100.0 #weight algorithm
