debug: true
joint_states_pub_name: /planning/joint_states #can show in urdf file, "/joint_states" for debug
uav_state_sub_name: /uav/root_link/odom

play_file_flag: true
control_test_flag: false #approaching test, "true" for debug

# red box
box_x: 1.005
box_y: 0.443
box_z: 0.2
box_offset_x: -0.4 # recycle box 
