aerial_transportation_plugin_name: aerial_transportation/hydrus

joint_motors_sub_name: /motor_states/joints_port

nav_vel_limit: 0.3
vel_nav_threshold: 0.2

object_approach_offset_x: -0.15
object_approach_offset_y: 0.3

approach_pos_threshold: 0.1
approach_count: 1.0
object_head_direction: true

object_height: 0.035 # set to the grasp height
grasping_height_threshold: 0.005
grasping_height_offset: 0.0

ascending_speed: 0.1
transportation_threshold: 0.15
transportation_count: 1.0

torque_min_threshold: 0.2
torque_max_threshold: 0.55

modification_delta_angle: 0.01

box_offset_y: 0.3

j1:
        approach_angle: 0.8
        hold_angle: 1.39  #tighten_angle: 0.08 # + 0.08rad(5deg)

j2:
        approach_angle: 1.15
        hold_angle: 1.56
        tighten_angle: 0.08 # + 0.08rad(5deg)

j3:
        approach_angle: 0.8
        hold_angle: 1.46
        tighten_angle: 0.08 # + 0.08rad(5deg)


# for the kinematics of hydrus3
link_length: 0.44
link_radius: 0.15 #real is 0.15 + 0.9(sponge)
link_num: 4

tighten_delta_angle: 0.14 #old: 0.12
approach_delta_angle: -0.4