motion_func_rate: 0

# inverse kinematics
differential_kinematics_count: 1000
actuator_state_sub_name: /dragon/joint_states
actuator_state_pub_name: /dragon/joint_states

# discrete path filter
discrete_path_filter_flag: true
cutoff_freq: 30.0

# discrete path resampling
resampling_flag: false # true

debug: false
start_state_x: 0.0
start_state_y: 0.0
start_state_z: 0.3
start_state_roll: 0.0
start_state_pitch: 0.0
start_state_yaw: 0.0

## joint init and goal
start_joint1_pitch: 0.0
start_joint1_yaw: 1.57  
start_joint2_pitch: 0.0
start_joint2_yaw: 1.57
start_joint3_pitch: 0.0
start_joint3_yaw: 1.57

## return locaton
return_delay: 10.0
final_pos_x: 0.3
final_pos_y: 0.9
final_yaw: 1.57

# cost
differential_kinematics_cost:
        cartesian_constraint:
                verbose: true
        state_vel:
                verbose: true
                w_joint_vel: 0.001
                w_root_translational_vel: 0.005 #0.001
                w_root_rotational_vel: 0.005 #0.001

# constraint
differential_kinematics_constraint:
        state_limit:
                verbose: true
                joint_vel_thre: 0.005 # 0.17
                root_translational_vel_thre: 0.005 # 0.1
                root_rotational_vel_thre: 0.005 #0.17
                joint_vel_constraint_range: 0.11
                joint_vel_forbidden_range: 0.02
                vebose: true
        stability:
                verbose: true
        collision_avoidance:
                verbose: true
                collision_distance_constraint_range: 0.05 # 0.08 (2018.05.10)
                collision_distance_forbidden_range: 0.02  #0.05 (2018.05.10)
        link_attitude:
                verbose: true
                roll_angle_thre: 1.5
                pitch_angle_thre: 1.0
        overlap:
                verbose: true
additional_constraint_list:
        - differential_kinematics_constraint/link_attitude
        - differential_kinematics_constraint/overlap
stability_margin_thre: 0.3
f_max: 22.0
f_min: 10.0